apiVersion: batch/v1
kind: Job
metadata:
  name: prep-db
  namespace: default
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: prep-db
        image: postgres:9.6
        command: ['psql']
        args: ['-c', 'CREATE EXTENSION IF NOT EXISTS pg_trgm;']
        env:
        - name: PGDATABASE
          value: postgres
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresSecret | quote }}
              key: database-server
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresSecret | quote }}
              key: database-username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresSecret | quote }}
              key: database-password
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresSecret | quote }}
              key: port
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    database:
      credentialsSecretName: {{ .Values.postgresSecret | quote }}
    imagePullSecretName: {{ .Values.pullSecret | quote }}
    registryBackends:
      - name: default
        credentialsSecretName: {{ .Values.s3Secret | quote }}
        s3:
          bucketName: {{ .Values.bucketName | quote }}
          host: {{ printf "s3.%s.amazonaws.com" .Values.region | quote }} 
  redis:
    credentialsSecretName: {{ .Values.redisSecret | quote }}